set nocompatible
source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin
if has("gui_running")
    set encoding=utf-8
    set fileencodings=ucs-bom,utf-8,chinese,prc,taiwan,latin-1

    if has("win32")
        set fileencoding=chinese
    else
        set fileencoding=utf-8
    endif
    let &termencoding=&encoding
    " 解决菜单乱码
    source $VIMRUNTIME/delmenu.vim
    source $VIMRUNTIME/menu.vim
    " 解决consle输出乱码
    language messages zh_CN.utf-8
endif
set diffexpr=MyDiff()
function MyDiff()
    let opt = '-a --binary '
    if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
    if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
    let arg1 = v:fname_in
    if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
    let arg2 = v:fname_new
    if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
    let arg3 = v:fname_out
    if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
    let eq = ''
    if $VIMRUNTIME =~ ' '
        if &sh =~ '\<cmd'
            let cmd = '""' . $VIMRUNTIME . '\diff"'
            let eq = '"'
        else
            let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
        endif
    else
        let cmd = $VIMRUNTIME . '\diff'
    endif
    silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3 . eq
endfunction
set nu
set nobackup
set guioptions=r
let &termencoding=&encoding
set fileencodings=utf-8,gbk,ucs-bom,cp936
set incsearch
set shiftwidth=4
winpos 0 435
set lines=20 columns=130
set autoindent
set tabstop=4 "设置tab键的宽度
setlocal noswapfile "不要生成swap文件，当buffer被丢弃的时候隐藏它
set bufhidden=hide 
if has("win32")
    set guifont=Courier_New:h13:cANSI
    set guifontwide=YaHei\ Consolas\ Hybrid:h10
endif
map <F3> :NERDTreeToggle<CR>
imap <F3> <ESC>:NERDTreeToggle<CR>
winpos 0 435
set lines=25 columns=170
set autoindent
:map <F11> :!start GVimWindow.exe<CR>
:map <C-F11> :!start GVimWindow.exe "ontop"<CR>
:map <S-F11> :!start GVimWindow.exe "200"<CR>
:map <F12> :!start GVimWindow.exe
"colorscheme murphy
"colorscheme torte
"colorscheme desert "灰色背景
"colorscheme blackboard  "灰色背景
colorscheme pablo  "灰色背景


